export const joinApplication = "emailRecipient.joinApplicationRecipient"
export const donationApplication = "emailRecipient.donationApplicationRecipient"
export const assistanceApplication= "emailRecipient.assistanceApplicationRecipient"
export const upgradeDonation = "emailRecipient.upgradeDonationRecipient"
export const feedback = "emailRecipient.feedbackRecipient"